apiVersion: v1
kind: Pod
metadata: 
  name: pod-volume
spec:
  containers: 
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /shared-volume
          name: first-volume

    - name: jenkins-container
      image: jenkins:alpine
      volumeMounts:
        - mountPath: /shared-volume
          name: first-volume
  volumes: 
    - name: first-volume
      hostPath:
        path: /
        type: Directory