apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deployments-example
spec: 
  replicas: 3
  template: 
    metadata: 
      name: nginx
      labels:
        app: nginx-1
    spec: 
      containers: 
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
  selector: 
    matchLabels: 
      app: nginx-1